---
- name: "Fetch java from Oracle"
  shell: "wget --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{jdk_url}} -O /tmp/java8.tar.gz"

- name: "Unpack java to install path"
  shell: tar -zxf /tmp/java8.tar.gz -C "{{jdk_install_path}}"

- name: "Update system to use new java"
  shell: update-alternatives --install /usr/bin/java java "/opt/jdk/jdk{{jdk_version}}/bin/java" 100
  become: true
